#
# Appveyor build
#
# @author Natesh Narain <nnaraindev@gmail.com>

os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-retro

configuration: Release

before_build:
  - cd c:\projects\gameboycore-retro
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF

build:
  project: c:\projects\gameboycore-retro\build\gameboycore_libretro.sln
  verbosity: minimal

after_build:
  - msbuild C:\projects\gameboycore-retro\build\PACKAGE.vcxproj /verbosity:quiet

artifacts:
- path: .\build\gameboycore_libretro-*-win*.exe
  name: installer

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: +F7/lKFe9fc9q4w0lCpc9tR1H4JucHiE7WuevfJCaWOeU/5ul8QojqNACB6ODFgT
  artifact: installer
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
  force_update: true
